### ISSUE TITLE
contribution

### ISSUE THREAD

**Issue by aahemm** [lnxpy/codehub#1]
Hi Ali Reza, 
I'd like to know how can we contribute to this project.
Thanks

**Comment by lnxpy** [comment]
Hi dear Aliakbar,

That's so simple as [Github has described it in this way](https://opensource.guide/how-to-contribute/). Unfortunately, all enthusiast contributors have to wait till the first stable version gets released.

Thanks for considering so far. Much appreciate that. :heart:
