### ISSUE TITLE
secret key must be SECRET !

### ISSUE THREAD

**Issue by mohsenFN** [lnxpy/CodeHub#4]
I have noticed that your [secret_key](https://github.com/lnxpy/CodeHub/blob/master/codehub/settings.py) is available for public and based on Django's docs it should be secret and also it's much better to read it from a .txt file.

https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/#secret-key

**Comment by lnxpy** [comment]
I just forgot this part. Thanks for mentioning. I'll check this out.
